-- Sample Data for Virtual Event Organizer
-- This file contains sample data that should be inserted AFTER users are registered through Supabase Auth
-- Run this AFTER the main schema.sql has been executed and users have been created

-- Note: Replace the UUIDs below with actual user IDs from auth.users table
-- You can get these by running: SELECT id FROM auth.users;

-- Sample Events (replace organizer_id with actual user ID from auth.users)
-- Note: These UUIDs are generated using uuid_generate_v4() - replace organizer_id with real user IDs
INSERT INTO public.events (id, organizer_id, title, description, start_date, end_date, capacity, status, is_public) VALUES
    ('123e4567-e89b-12d3-a456-426614174004', 'REPLACE_WITH_ACTUAL_USER_ID', 'AI Conference 2024', 'Annual AI and Machine Learning Conference featuring cutting-edge research and industry insights', '2024-12-01 09:00:00+00', '2024-12-01 18:00:00+00', 500, 'published', true),
    ('123e4567-e89b-12d3-a456-426614174005', 'REPLACE_WITH_ACTUAL_USER_ID', 'Dev Meetup December', 'Monthly Developer Meetup with networking and tech talks', '2024-12-15 19:00:00+00', '2024-12-15 21:00:00+00', 100, 'published', true),
    ('123e4567-e89b-12d3-a456-426614174006', 'REPLACE_WITH_ACTUAL_USER_ID', 'Web Development Webinar Series', 'Weekly webinars covering modern web development practices', '2024-12-10 14:00:00+00', '2024-12-10 15:30:00+00', 200, 'published', true);

-- Sample Sessions (replace event_id with actual event IDs created above)
INSERT INTO public.sessions (id, event_id, title, description, speaker, speaker_bio, speaker_email, start_time, end_time, status) VALUES
    ('123e4567-e89b-12d3-a456-426614174007', '123e4567-e89b-12d3-a456-426614174004', 'Advanced Machine Learning', 'Deep dive into advanced ML techniques including deep learning, reinforcement learning, and neural architecture search', 'Dr. Sarah Johnson', 'Senior ML Engineer at TechCorp with 10+ years experience in AI research', 'sarah@techcorp.com', '2024-12-01 10:00:00+00', '2024-12-01 11:00:00+00', 'scheduled'),
    ('123e4567-e89b-12d3-a456-426614174008', '123e4567-e89b-12d3-a456-426614174004', 'AI Ethics Panel', 'Discussion on ethical AI development, bias mitigation, and responsible AI practices', 'Panel of Experts', 'Leading AI ethicists and researchers', 'ethics@aiconf.com', '2024-12-01 14:00:00+00', '2024-12-01 15:00:00+00', 'scheduled'),
    ('123e4567-e89b-12d3-a456-426614174009', '123e4567-e89b-12d3-a456-426614174005', 'React 2024: What''s New', 'Overview of the latest React features and best practices for 2024', 'Alex Chen', 'Frontend Developer and React contributor', 'alex@devmeetup.com', '2024-12-15 19:30:00+00', '2024-12-15 20:30:00+00', 'scheduled'),
    ('123e4567-e89b-12d3-a456-426614174010', '123e4567-e89b-12d3-a456-426614174006', 'Next.js Performance Tips', 'Optimizing Next.js applications for better performance and user experience', 'Maria Rodriguez', 'Full-stack developer specializing in React and Next.js', 'maria@webdev.com', '2024-12-10 14:15:00+00', '2024-12-10 15:15:00+00', 'scheduled');

-- Sample Users (these will be created through Supabase Auth, but we can add additional profile data)
-- Note: These should be inserted AFTER users register through Supabase Auth
-- Example: After a user registers with email 'organizer@techconf.com', update their profile:

-- UPDATE public.users SET 
--   name = 'Tech Conference Organizer',
--   role = 'organizer',
--   company = 'TechCorp',
--   job_title = 'Event Manager',
--   bio = 'Passionate about organizing tech events and bringing communities together'
-- WHERE email = 'organizer@techconf.com';

-- Sample Notifications (these will be created through the application)
-- Example notifications that might be sent:
-- - Welcome messages for new registrations
-- - Schedule change notifications
-- - Networking connection requests
-- - Event reminders

-- Sample Analytics Data (this will be generated by the application)
-- The event_analytics table will be populated automatically as users interact with the system

-- Instructions for inserting sample data:
-- 1. First, register users through Supabase Auth (or use the Supabase dashboard)
-- 2. Get the user IDs from auth.users table
-- 3. Replace 'REPLACE_WITH_ACTUAL_USER_ID' with actual user IDs
-- 4. Run the INSERT statements above
-- 5. The application will handle creating attendees, connections, and notifications as users interact with the system
