# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'UncleTaxim' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static

  # Firebase pods
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseFunctions'
  
  # Stripe SDK
  pod 'StripePaymentSheet', '~> 24.0'

end
