export interface User {
  id?: string; // UUID is generated by the database
  username: string;
  email: string;
  passwordHash: string;
  createdAt?: Date; // Timestamp generated by the database
  updatedAt?: Date; // Timestamp generated by the database
}

export interface Category {
  id?: string; // UUID is generated by the database
  userId: string;
  name: string;
  type: 'expense' | 'income';
  createdAt?: Date;
  updatedAt?: Date;
}

export interface Transaction {
  id?: string; // UUID is generated by the database
  userId: string;
  categoryId?: string | null; // Optional, can be null if category is deleted
  amount: number;
  type: 'expense' | 'income';
  date: string; // YYYY-MM-DD format
  description?: string | null;
  createdAt?: Date;
  updatedAt?: Date;
}
